baseURL = 'https://avisoventures.com/'
languageCode = 'en-us'
title = 'Aviso Ventures'
enableRobotsTXT = true
copyright = "&copy; Aviso Ventures"
googleAnalytics = 'G-MEASUREMENT_ID'

disableKinds = ["sitemap"]

